Correctly reading image & turning on LED
- last thing: Need to fix robot motion
Error: [ERROR] [1648220633.617375544]: Validation failed: Missing velocity data for trajectory pt 0
- Maybe try giving an initial position before having it manual go through the rest of the way points